server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    ru.unit.techno.device.registration.core.impl: INFO

spring:
  application:
    name: device-registration-core
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: device_registration_service
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_MAIN_DSN:jdbc:postgresql://localhost:5432/unit_techno?currentSchema=device_registration_service}
    username: ${DATASOURCE_MAIN_USERNAME:device_registration_admin}
    password: ${DATASOURCE_MAIN_PASSWORD:squd}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true